"""Add comment and reply fields to auto task

Revision ID: 62d2fe94700e
Revises: 60cd5c95fde1
Create Date: 2026-05-17 12:14:11.615871
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62d2fe94700e'
down_revision: Union[str, None] = '60cd5c95fde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_auto_comment', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment_templates', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('comment_instruction', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('enable_auto_reply', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reply_templates', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reply_instruction', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('total_comments', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_replies', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_tasks', schema=None) as batch_op:
        batch_op.drop_column('total_replies')
        batch_op.drop_column('total_comments')
        batch_op.drop_column('reply_instruction')
        batch_op.drop_column('reply_templates')
        batch_op.drop_column('enable_auto_reply')
        batch_op.drop_column('comment_instruction')
        batch_op.drop_column('comment_templates')
        batch_op.drop_column('enable_auto_comment')

    # ### end Alembic commands ###
