type: yolov8
name: xhs_ui_detect_v2
display_name: XHS UI Detect (YOLOv8s)
model_path: best.onnx
input_width: 1280
input_height: 1280
score_threshold: 0.45
nms_threshold: 0.45
confidence_threshold: 0.45
classes: ['位置', '已点赞', '输入评论', '查看评论列表', '收藏', '首页', '消息', '已收藏', '赞', '发现', '我', '已关注', '发送', '市集', '视频帖子', '关注', '回复', '帖子封面', '返回']
